#!/usr/bin/env python
import sys, os, glob, re, commands

r = re.compile(r"(20..-..-..)")
for fn in glob.glob("*.py"):
    st, op = commands.getstatusoutput("bzr log -l1 --line " + fn)
    m = r.search(op)
    date, = m.groups()

    st, op = commands.getstatusoutput("sed -i 's/Last changed.*/Last changed: %s/' %s" % (date, fn))
