#!/usr/bin/env python

import sys
from ufl.algorithms import FormData, load_forms, validate_form, ufl2latex, tree_format

# Get commandline options
args = sys.argv[1:]
if not args:
    print "Expecting .ufl file names."
    sys.exit(-1)
filenames = args

# Handle each form file separately
for filename in args:
    print
    if not filename.endswith(".ufl"):
        print "Warning: Filename '%s' doesn't end with .ufl." % filename

    # Load form file, which triggers many consistency
    # checks while the form is being built
    print "Loading form file '%s'" % filename
    formdatas = load_forms(filename)

    # Analyse validity of forms
    for fd in formdatas:
        form = fd.form
        name = fd.name
        
        errors = validate_form(form)
        print
        if errors:
            print "Found errors in form '%s':" % name
            print errors
        else:
            print "Found no errors in form '%s'." % name
    
    # Print information about all forms
    for fd in formdatas:
        form = fd.form
        name = fd.name
        
        # Pretty-print form information
        print
        print "Form info:"
        print "    Name: '%s'" % name
        print "    Rank:", fd.rank
        print "    Number of coefficients:", fd.num_coefficients
        print "    Number of cell integrals:", len(form.cell_integrals())
        print "    Number of exterior facet integrals:", len(form.exterior_facet_integrals())
        print "    Number of interior facet integrals:", len(form.interior_facet_integrals())
        print "    Elements used:"
        for e in fd.unique_elements:
            print "       ", repr(e)
        print "    Basisfunctions:"
        for v in fd.basisfunctions:
            print "       ", repr(v)
        print "    Coefficients:"
        for w in fd.coefficients:
            print "       ", repr(w)
        print
        print "Form representation:"
        print repr(form)
        print
        print "Form pretty-print:"
        print str(form)
        print
        print "Form tree formatting:"
        tree = tree_format(form)
        print tree
        print
        print "Form LaTeX code:"
        latex = ufl2latex(form)
        print latex
    print

