#!/usr/bin/env python

import sys
import ufl
import ufl.utilities

# Get commandline options
if len(sys.argv) != 2:
    print "Expecting a single argument, the form file name."
    sys.exit(-1)
filename = sys.argv[1]

# Load form file, which triggers many consistency
# checks while the form is being built
print "Loading form file '%s'" % filename
forms = ufl.utilities.load_forms(filename)

# Analyse validity of forms
for k,v in forms:
    errors = ufl.utilities.analyse_form(v)
    print
    if errors:
        print "Found errors in form '%s':" % k
        print errors
    else:
        print "Found no errors in form '%s'." % k

# Print information about all forms
for name, form in forms:
    # Extract information about forms
    basisfunctions = ufl.utilities.basisfunctions(form)
    coefficients = ufl.utilities.coefficients(form)
    elements = ufl.utilities.unique_elements(form)
    rank = len(basisfunctions)
    num_coefficients = len(coefficients)
    
    # Pretty-print form information
    print
    print "Form: '%s'" % name
    print "Rank:", rank
    print "Number of coefficients:", num_coefficients
    print "Elements used:"
    for e in elements:
        print repr(e)
    print "Basisfunctions:"
    for v in basisfunctions:
        print repr(v)
    print "Coefficients:"
    for w in coefficients:
        print repr(w)
    print "Form representation:"
    print repr(form)

print

