#!/usr/bin/env python

# Get commandline options # TODO: Use proper option parsing
import sys
args = sys.argv[1:]
if len(args) != 1:
    print "Missing form file name."
    print "Got args: ", " ".join(args)
    sys.exit(-1)
uflfilename = args[0]

# TODO: safer filename conversion
basename = uflfilename.replace(".ufl", "")
latexfilename = basename + ".tex"
pdffilename = basename + ".pdf"

# Compile PDF file
from ufl.algorithms import uflfile2pdf
uflfile2pdf(uflfilename, latexfilename, pdffilename)

