#!/usr/bin/env python

# Get commandline options # TODO: Use proper option parsing
import sys
args = sys.argv[1:]

compile = "-c" in args
if compile: args.remove("-c")

if len(args) != 1:
    print "Missing form file name."
    print "Got args: ", " ".join(args)
    sys.exit(-1)
uflfilename = args[0]

# TODO: safer filename conversion
basename = uflfilename.replace(".ufl", "")
texfilename = basename + ".tex"
pdffilename = basename + ".pdf"

# Compile .ufl file into PDF file
from ufl.algorithms import ufl2pdf
ufl2pdf(uflfilename, texfilename, pdffilename, compile=compile)

