#!/usr/bin/env python

import os, sys
import webbrowser
import ufl
from ufl.algorithms import load_forms, validate_form, ufl2latex

# Get commandline options

# TODO: Use proper option parsing
args = sys.argv[1:]

if len(args) != 1:
    print "Missing form file name."
    sys.exit(-1)
filename = args[0]
basename = filename.replace(".ufl", "") # TODO: safer filename conversion
texfilename = basename + ".tex"
pdffilename = basename + ".pdf"

os.system("ufl2latex %s -o %s" % (filename, texfilename))
os.system("pdflatex %s %s" % (texfilename, pdffilename))

