#!/usr/bin/env python

import sys
import webbrowser
import ufl
from ufl.algorithms import load_forms, validate_form, ufl2latex

# Get commandline options

args = sys.argv[1:]

# Pass latex code to www.texify.com (doesn't seem to work for long forms)
enable_browser = False
if "-w" in args:
    enable_browser = True
    args.remove("-w")

if len(args) != 1:
    print "Missing form file name."
    sys.exit(-1)
filename = args[0]

# Load form file, which triggers many consistency
# checks while the form is being built
forms = load_forms(filename)

# Analyse validity of forms
found_errors = False
for k,v in forms:
    errors = validate_form(v)
    if errors:
        print "Found errors in form '%s':" % k
        print errors
        found_errors = True
if found_errors:
    sys.exit(-1)

# Define template for overall document
latex = r"""
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\section{UFL Forms from file %(filename)s}
"""

# Generate latex code for each form
for name, form in forms:
    l = ufl2latex(form)
    latex += r"\subsection{Form %s}\n" % name
    latex += r"\[\n%s\n\]\n" % l
    if enable_browser:
        webbrowser.open("http://www.texify.com/$%s$" % l.replace(" ",""))

latex += r"""
\end{document}
"""

if latexfile:
    f = open(latexfile, "w")
    f.write(latex)
    f.close()
else:
    print latex

