# This workflow will install Python dependencies and run tests
name: UFL CI

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        default: "3.12"
        type: string
      os:
        description: "Operating system"
        default: "ubuntu-latest"
        type: string
      deploy:
        description: "Upload to coveralls"
        default: false
        type: boolean

  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version"
        default: "3.12"
        type: string
      os:
        description: "Operating system"
        default: "ubuntu-latest"
        type: string
      deploy:
        description: "Upload to coveralls"
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install UFL
        run: python -m pip install .[ci]

      - name: Run unit tests
        # Run tests twice, coverage raises warnings, thus does not pass with -W error
        run: |
          python -m pytest -W error -n auto test/
          python -m pytest -n auto --cov=ufl/ --junitxml=junit/test-results-${{ inputs.os }}-${{ inputs.python-version }}.xml test/

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v5
        with:
          name: test-results-${{ inputs.os }}-${{ inputs.python-version }}
          path: junit/test-results-${{ inputs.os }}-${{ inputs.python-version }}.xml
          retention-days: 2
          if-no-files-found: error

      - name: Install coveralls
        run: pip install coveralls

      - name: Upload to Coveralls
        if: ${{ inputs.deploy }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls
